### ISSUE TITLE
[BUG] fails to build with github.com/olekukonko/tablewriter 1.1.3

### ISSUE THREAD

**Issue by daniel-baumann** [maypok86/otter#173]
Hi,

I'm uploading otter to Debian (it's a depends of another package), however, it fails to build in current Debian unstable.

If I see correctly, then it's because otter doesn't work with tablewriter 1.1.3 (from January 2026):

```
[...]
# github.com/maypok86/otter/benchmarks/simulator/internal/report/table
src/github.com/maypok86/otter/benchmarks/simulator/internal/report/table/report.go:60:5: tw.SetBorders undefined (type *tablewriter.Table has no field or method SetBorders)
src/github.com/maypok86/otter/benchmarks/simulator/internal/report/table/report.go:60:28: undefined: tablewriter.Border
src/github.com/maypok86/otter/benchmarks/simulator/internal/report/table/report.go:61:5: tw.SetCenterSeparator undefined (type *tablewriter.Table has no field or method SetCenterSeparator)
src/github.com/maypok86/otter/benchmarks/simulator/internal/report/table/report.go:62:5: tw.SetHeader undefined (type *tablewriter.Table has no field or method SetHeader)
[...]
```

Any chance you could update otter and bump the dependency to the current tablewriter 1.1.3 version?

Regards,
Daniel

**Comment by daniel-baumann** [comment]
and a little later down in the buildlog I also see:

```
# github.com/maypok86/otter/docs/examples/wrapper
runtime.main_main·f: function main is undeclared in the main package
```

**Comment by maypok86** [comment]
Hi, this is quite strange because the [package](https://pkg.go.dev/github.com/maypok86/otter/v2) has no dependencies on docs and benchmarks. Are you downloading the entire repository for some reason? And it seems you're compiling it in a special way, because the tablewriter version is correctly specified in go.mod for benchmarks and everything works fine with it.
